#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\IndexController::redirectHome
  defaults:
    route: /fr
    permanent: true
